examples/vision/meta_mnist.py, learn2learn/data/task_generator.py
The API would change from current
```python
tg = TaskGenerator(dataset, classes = [0,1,2,3], ways = 3)
tg.sample(shots=1)
tg.sample( classes=[1,2,3])
```
to 
```python
tg = TaskGenerator(dataset, classes = [0,1,2,3], ways = 3, shots=1, tasks = [[1,2,3], [0,1,2]...)
tg = TaskGenerator(dataset, classes = [0,1,2,3], ways = 3, shots=1, tasks = 100)
tg.sample() # this function earlier required shots to be defined, now it can be defined durining init of the TG object
tg.sample(task=[1,2,3])
next(tg) # this function wasn't earlier defined
```
=> [WIP] #12 Add Tasks to TaskGenerator

learn2learn/data/task_generator.py, tests/unit/task_generator/task_generator_test.py
When `tasks` were set to `None` earlier then we were generating all the permutations which could've resulted in OOM. Now we randomly sample on the fly. 
This PR also adds a test case to validate the behavior.
=> Added test and support for infinite tasks generation

examples/vision/maml_omniglot.py, tests/integration/maml_omniglot_test.py
Fixes #88 
Swaps `deepcopy(maml)` by `maml.clone()` for validation and testing  tasks in the Omniglot example and unit test.
If you make major changes to the core library, please copy-paste the output of running `make alltests` below.
~~~shell
test_final_accuracy (integration.maml_omniglot_test.MAMLOmniglotIntegrationTests) ... Downloading https://github.com/brendenlake/omniglot/raw/master/python/images_background.zip to ./data/omniglot-py/images_background.zip
9469952it [00:01, 7913811.97it/s] …
=> Fix Omniglot memory leak.

CHANGELOG.md, Makefile, README.md, docs/pydocmd.yml, learn2learn/vision/datasets/__init__.py, learn2learn/vision/datasets/fc100.py, learn2learn/vision/datasets/fgvc_aircraft.py, learn2learn/vision/datasets/tiered_imagenet.py, learn2learn/vision/datasets/vgg_flowers.py, tests/integration/protonets_miniimagenet_test_notravis.py, tests/unit/vision/fc100_test.py, tests/unit/vision/fgvc_aircraft_test.py, tests/unit/vision/tiered_imagenet_test_notravis.py, tests/unit/vision/vgg_flowers_test.py
This PR adds scripts to download several commonly used few-shot learning vision datasets, including:
* FC100,
* tiered-ImageNet,
* VGG Flowers, and
* FGVC Aircraft.
For the first two, we replicate the original splits of the authors.
For the latter two, we replicate the splits of Meta-Dataset (Triantafillou et al, 2020).
All implementations include docs and tests.
If you make major changes to the core library, please copy-paste the output of running `make alltests` below.
~~~shell
test_final_accuracy (integration.maml_omniglot_test.MAMLOmniglotIntegrationTests) …
=> Add more vision datasets.

examples/vision/maml_miniimagenet.py, examples/vision/maml_omniglot.py
Fixes #108 
In Vision (omniglot & miniimagenet) examples in MAML, testing was taking place in every training iteration (which is redundant & adds to computational cost).
Fix: Move it outside.
=> Move testing outside training loop

learn2learn/vision/datasets/cifarfs.py, learn2learn/vision/datasets/fc100.py, learn2learn/vision/datasets/fgvc_aircraft.py, learn2learn/vision/datasets/full_omniglot.py, learn2learn/vision/datasets/mini_imagenet.py, learn2learn/vision/datasets/tiered_imagenet.py, learn2learn/vision/datasets/vgg_flowers.py
**Bug:** When trying to run some of the vision examples, it would return the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '~/data'`
This is because the string '~/data' was not being converted to the actual path (using `os.path.expanduser`).
**Fix:** All dataset files now turn their path argument into the full path using os.path.expanduser.
**Consistency:** Some of the datasets were already using _os.path.expanduser_ when initialized. Some were expecting the argument would be already pre-processed before initialized. Now all the datasets expect the path in the form of "~/data" or "./data" and convert the variable during initialization. Also some of the datasets were passing the path `root` as argument to a function within the same class when they could just use …
=> Fix path bug & improved consistency across dataset files

MANIFEST.in, Makefile, setup.py
Fixes #111 
This PR fixes the installation issue when running `python setup.py install` on a cloned repo.
The changes are to include all files `learn2learn/` so that the `.so` files are copied over. Moreover, I also added `zip_safe=False` to the setuptools command, as recommended on the Cython documentation page.
References:
* https://stackoverflow.com/a/32537661
* https://cython.readthedocs.io/en/latest/src/quickstart/build.html#building-a-cython-module-using-distutils
=> Fix Cython compilation when installing from sources.

examples/vision/maml_omniglot.py, learn2learn/data/task_dataset.pxd, learn2learn/data/task_dataset.pyx, learn2learn/data/transforms.pyx, setup.py, tests/integration/maml_omniglot_test.py
This PR accelerates task initialization by delegating it to the first task transform.
This PR also introduces the `FusedNWaysKShots`, which efficiently combines the `FilterLabels`, `NWays`, and `KShots` task transforms. On Omniglot, this translates to a 5x speed up in task sampling time.
~~~shell
test_final_accuracy …
=> Move task initialization to transforms.

examples/vision/anil_fc100.py, examples/vision/maml_miniimagenet.py, examples/vision/reptile_miniimagenet.py
Some examples (anil_fc100, maml_miniimagenet and reptile_miniimagenet) were using training labels in validation or test sets
=> Fix using training labels in validation or test in some examples

learn2learn/utils.py, tests/integration/maml_miniimagenet_test_notravis.py, tests/integration/protonets_miniimagenet_test_notravis.py, tests/unit/utils_test.py
This small PR speeds-up `l2l.clone_module()` by replacing the deepcopy with a careful shallow copy.
On mini-ImageNet, this translates to a 35% speed-up.
~~~shell
test_adaptation (unit.algorithms.maml_test.TestMAMLAlgorithm) ... ok
test_allow_nograd …
=> Faster clone_module.

Makefile, learn2learn/data/transforms.pyx, setup.py
Makes Cython transforms compatible with pickle by adding a `__reduce__` method.
This is useful for pickling them to file or to share them via multi-processing.
Reference: [https://github.com/cython/cython/blob/master/tests/run/reduce_pickle.pyx](https://github.com/cython/cython/blob/master/tests/run/reduce_pickle.pyx)
=> Make transforms compatible with pickle.

learn2learn/data/transforms.pyx
- `sum(list_of_list, [])` is inefficient. Read [here](https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-list-of-lists)
- A small typo fix in the code.
PS : We can merge it with some other bigger PR if we want to avoid small 1 line commits.
=> Use iterools.chain instead of sum to flatten list + Fix variable Typo 

.travis.yml, CHANGELOG.md, learn2learn/utils.py, learn2learn/vision/datasets/vgg_flowers.py, tests/unit/utils_test.py
clone_module now returns the object if it is not an instance of torch.nn.Module.
As a minor fix to tests on travis, I also changed `tarfile.TarFile` to `tarfile.open` in VGG.
=> Improve clone_module support for non Module objects.

CHANGELOG.md, Makefile, docs/pydocmd.yml, examples/vision/maml_miniimagenet.py, examples/vision/maml_omniglot.py, learn2learn/vision/__init__.py, learn2learn/vision/benchmarks/__init__.py, learn2learn/vision/benchmarks/cifarfs_benchmark.py, learn2learn/vision/benchmarks/fc100_benchmark.py, learn2learn/vision/benchmarks/mini_imagenet_benchmark.py, learn2learn/vision/benchmarks/omniglot_benchmark.py, learn2learn/vision/benchmarks/tiered_imagenet_benchmark.py, learn2learn/vision/datasets/cifarfs.py, learn2learn/vision/datasets/fc100.py, learn2learn/vision/datasets/mini_imagenet.py, learn2learn/vision/models.py, tests/unit/vision/benchmarks_test.py, tests/unit/vision/cifarfs_test.py, tests/unit/vision/fc100_test.py
Adds benchmark interface for vision datasets.
This PR adds implementation, documentation, and tests for `l2l.vision.benchmarks`. The new functionality helps remove some boilerplate code when comparing algorithms on standardized benchmarks.
~~~shell
test_adaptation …
=> Add l2l.vision.benchmarks interface.

examples/rl/cavia_trpo.py, examples/rl/policies.py
I altered the maml_trpo sample to implement CAVIA (Paper: https://arxiv.org/abs/1810.03642 , Paper code: https://github.com/lmzintgraf/cavia)
Basically, only the context parameters are updated in the inner-loop (other params stay the same), therefore I implemented a new policy (CaviaDiagNormalPolicy) and changed the TRPO train loop.
=> add: CAVIA implementation

examples/rl/cavia_trpo.py, examples/rl/maml_trpo.py, examples/rl/maml_trpo_metaworld.py, examples/rl/policies.py
If example maml_trpo.py is run with cuda following error occurs:
```bash
Traceback (most recent call last):
File "maml_trpo.py", line 218, in <module>
main(cuda=1)
File "maml_trpo.py", line 158, in main
train_episodes = task.run(clone, episodes=adapt_bsz)
File "/home/jan/workspace_python/maml-torch/cherry/cherry/envs/runner_wrapper.py", line 117, in run
action = get_action(self._current_state)
File "/home/jan/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
result = self.forward(*input, **kwargs)
File "/home/jan/workspace_python/forks/learn2learn/examples/rl/policies.py", line 95, in forward
density = self.density(state)
File "/home/jan/workspace_python/forks/learn2learn/examples/rl/policies.py", line 86, in density
loc = …
```
=> Fixed some examples with cuda usage

learn2learn/data/utils.py, learn2learn/utils.py
Fixes #188 
The warning is triggered by calling `._apply()` for non RNN modules. 
=> Fix clone_module to suppress "Accessing .grad" warning.

CHANGELOG.md, docs/pydocmd.yml, learn2learn/data/__init__.py, learn2learn/data/meta_dataset.pyx, tests/unit/data/metadataset_test.py
Adds FilteredMetaDataset and fixes length of UnionMetaDataset.
~~~shell
test_adaptation (unit.algorithms.gbml_test.TestGBMLgorithm) ... ok
test_allow_nograd (unit.algorithms.gbml_test.TestGBMLgorithm) ... Traceback (most recent call last):
File …
=> Adds FilteredMetaDataset and fixes length of UnionMetaDataset.

examples/vision/maml_miniimagenet.py
Fixes #190 
In the current example of MAML applied to mini-imagenet the averaged loss is averaged twice.
=> Fix double error normalisation in maml example

examples/vision/maml_omniglot.py
Similar to #196
Fixes an issue similar to #190 for the OmniGlot dataset.
The loss function already uses `mean` as it's aggregation, therefore the computed loss should not be re-normalised.
=> Fix omniglot double normalization issue

examples/rl/maml_dice.py
Change the learning rate for the inner loop from `meta_lr` to `adapt_lr` in the MAML DiCE example.
=> minor fix in RL example (MAML DiCE)

examples/vision/protonet_miniimagenet.py
Fixes #219 https://github.com/learnables/learn2learn/issues/219
Results of protonet_miniimagenet.py not matching reported results. (43 vs 49 )
Passing max_pool=True to convbase in the convnet of protonet_miniimagenet.py
=> Adding maxpool to match paper results

learn2learn/nn/kroneckers.py, tests/unit/nn/kroneckers_test.py
Fixes #220 
Makes KroneckerLinear more robust by adding support for one-dimensional inputs, making KroneckerLinear throw an exception if the input tensor dimensions are incorrect, and adding unit tests.
=> Make KroneckerLinear robust to unexpected inputs

learn2learn/algorithms/lightning/lightning_metaoptnet.py
Fixes the link to MetaOptNet (Meta-Learning with Differentiable Convex Optimization) Lightning [Source] in http://learn2learn.net/docs/learn2learn.algorithms/
=> Fix the link to Lightning module for MetaOptNet (Meta-Learning with Differentiable Convex Optimization) in docs

learn2learn/algorithms/lightning/lightning_anil.py
Fixes the link to ANIL Lightning `[Source]` in http://learn2learn.net/docs/learn2learn.algorithms/
=> Fix the link to Lightning module for Almost No Inner Loop (ANIL) in docs

learn2learn/algorithms/lightning/lightning_protonet.py
Fixes the link to ProtoNets Lightning `[Source]` in http://learn2learn.net/docs/learn2learn.algorithms/
=> Fix the link to Lightning module for Prototypical Networks in docs

learn2learn/algorithms/lightning/lightning_maml.py
Fixes the link to MAML Lightning `[Source]` in http://learn2learn.net/docs/learn2learn.algorithms/
=> Fix the link to Lightning module for Model-Agnostic Meta-Learning in docs

.github/workflows/python_unittest.yaml, CHANGELOG.md, docs/pydocmd.yml, learn2learn/algorithms/lightning/lightning_episodic_module.py, learn2learn/nn/misc.py, learn2learn/vision/models/__init__.py, learn2learn/vision/models/cnn4.py, learn2learn/vision/models/resnet12.py, learn2learn/vision/models/wrn28.py, setup.py, tests/unit/data/metadataset_test.py
* Adds an option to get the ResNet12 from TADAM, and WRN28 from Dhillon et al. 
* Adds `l2l.vision.models.get_pretrained_backbone` and backbone modules for CNN4, ResNet12, WRN28 (pretrained backbones from FEAT).
=> Add TADAM's version of ResNet12.

learn2learn/vision/models/cnn4.py
Change arguments of CNN4Bakcbone to match the defaults of CNN4 (good defaults for mini-ImageNet).
~~~shell
[PASTE HERE]
~~~
=> Match CNN4 and CNN4Backbone argumments, fix doc.

CHANGELOG.md, learn2learn/algorithms/lightning/lightning_episodic_module.py
Logging with `on_step = on_epoch = False` raises an error in PL 1.5 or greater.
~~~shell
[PASTE HERE]
~~~
=> Fix logging in PL 1.5

examples/vision/distributed_maml.py
Fixes #263 
Adds an example of using `torch.distributed` to train MAML (the DDP wrapper is not easily compatible with MAML).
=> Add example of distributed MAML.

CHANGELOG.md, learn2learn/vision/transforms.py, tests/unit/vision/transform_test_notravis.py
Fixes #267 
As discussed with @seba-1511, adds an option for RGB bands for Random Rotation.
=> Resolve issue #267

CHANGELOG.md, learn2learn/algorithms/meta_sgd.py, learn2learn/utils/__init__.py, tests/unit/algorithms/maml_test.py, tests/unit/algorithms/metasgd_test.py, tests/unit/data/metadataset_test.py
Fixes #284
Fix memory leak in `maml.py` and `meta-sgd.py` and add tests to `maml_test.py` and `metasgd_test.py` to check for possible future memory leaks. A test involving cloning parameters seems to fail, but my changes have nothing to do with it. 
If necessary, use the following space to provide context or more details.
~~~shell
make[1]: Entering directory '/home/kevin/Documents/umd_cp/research/open-source/learn2learn'
9464832it [00:01, …
=> Fix memory leak

examples/vision/anilkfo_cifarfs.py, examples/vision/metacurvature_fc100.py, examples/vision/protonet_miniimagenet.py
Using a named argument whose name does not correspond to a parameter of the __init__ method of the class being instantiated, resulted in a TypeError at runtime.
Fixed the arguments in 3 example files.
=> Wrong name for an argument in a class instantiation

examples/vision/reptile_miniimagenet.py
Added meta_lr_final parameter to indicate the final value of the meta learning rate. By setting meta_lr_final to a smaller value than meta_lr, the meta learning rate is effectively decayed during training. Before it was constant due to the bug of using meta_lr both times in the weighted sum. 
Fixes #[ISSUE NUMBER]
Replace this line by a one sentence summary of your PR.
If necessary, use the following space to provide context or more details.
~~~shell
[PASTE HERE]
~~~
=> Meta-learning rate in reptile example is not decaying (as of now).

learn2learn/utils/lightning.py
Fixes #346
pytorch lightning doesn't include `pl.callbacks.ProgressBar` anymore, so I replaecd it with `TQDMProgressBar` to fix import error
=> fix inheritance in NoLeaveProgressBar

CHANGELOG.md, examples/maml_toy.py
The MAML Toy example `examples/maml_toy.py` does not run due to a sigma parameter being sampled from a Normal distribution. That sigma is used to parameterise another Normal distribution, hence must be positive.
=> Fix maml_toy example

learn2learn/gym/envs/meta_env.py
Fixes #411
In meta_env.py. `super(MetaEnv, self).__init__()` is changed to `Env.__init__(self)`.
=> Fix MetaEnv initialization.
