examples/vision/meta_mnist.py
=> Fix determinism problem on meta-mnist example.

learn2learn/models.py
Partially fixes #13. It needs documentation and clean up, but I'd say let's merge it because other issues can already start to use those models.
=> Add learn2learn.models first draft.

learn2learn/data/task_generator.py, learn2learn/data/vision/FullOmniglot.py
=> Add FullOmniglot

examples/vision/meta_mnist.py, learn2learn/__init__.py, learn2learn/algorithms/base_learner.py, learn2learn/data/task_generator.py, learn2learn/data/vision/FullOmniglot.py, learn2learn/models.py
=> Don't sort in LabelEncoder

learn2learn/transforms/vision/__init__.py, learn2learn/transforms/vision/random_discrete_rotations.py
=> Add RandomDiscreteRotations.

docs/pydocmd.yml, examples/vision/maml_miniimagenet.py, learn2learn/algorithms/maml.py, learn2learn/data/task_generator.py, learn2learn/gym/envs/meta_env.py, learn2learn/gym/envs/mujoco/ant_direction.py, learn2learn/gym/envs/mujoco/ant_forward_backward.py, learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py, learn2learn/gym/envs/mujoco/humanoid_direction.py, learn2learn/gym/envs/mujoco/humanoid_forward_backward.py, learn2learn/gym/envs/particles/particles_2d.py, learn2learn/text/datasets/news_classification.py, learn2learn/utils.py, learn2learn/vision/datasets/__init__.py, learn2learn/vision/datasets/full_omniglot.py, learn2learn/vision/datasets/mini_imagenet.py, learn2learn/vision/models.py, learn2learn/vision/transforms.py
=> Adding docs miniimagenet

learn2learn/data/transforms.py, learn2learn/vision/datasets/cifarfs.py, learn2learn/vision/datasets/full_omniglot.py
Fixes #94 
Simply adds the `_bookkeeping` path to the classes. Also fixes linting for the KShots transform.
=> Add bookkeeping to Omniglot and CIFAR-FS.

CHANGELOG.md, Makefile, README.md, docs/pydocmd.yml, examples/vision/maml_miniimagenet.py, examples/vision/maml_omniglot.py, examples/vision/meta_mnist.py, examples/vision/protonet_miniimagenet.py, learn2learn/vision/datasets/__init__.py, learn2learn/vision/datasets/fc100.py, learn2learn/vision/datasets/fgvc_aircraft.py, learn2learn/vision/datasets/tiered_imagenet.py, learn2learn/vision/datasets/vgg_flowers.py, tests/integration/maml_miniimagenet_test_notravis.py, tests/integration/maml_omniglot_test.py, tests/integration/protonets_miniimagenet_test_notravis.py, tests/unit/vision/fc100_test.py, tests/unit/vision/fgvc_aircraft_test.py, tests/unit/vision/tiered_imagenet_test_notravis.py, tests/unit/vision/vgg_flowers_test.py
Fixes #99 
In examples, computes data indices using numpy instead of PyTorch to keep compatibility with PyTorch 1.1.0+.
=> Fix data indexing in examples.

docs/pydocmd.yml
This PR fixes an indentation issue in the pydoc.yml file preventing the table of content to properly appear on the vision documentation page.
=> Fix vision documentation TOC.

CHANGELOG.md, learn2learn/gym/envs/mujoco/__init__.py, learn2learn/gym/envs/mujoco/ant_direction.py, learn2learn/gym/envs/mujoco/ant_forward_backward.py, learn2learn/gym/envs/mujoco/dummy_mujoco_env.py, learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py, learn2learn/gym/envs/mujoco/humanoid_direction.py, learn2learn/gym/envs/mujoco/humanoid_forward_backward.py
Fixes #59 
If the import of `MujocoEnv` fails, replace it with a dummy class that delays the dependency error to the first method call.
=> Make Mujoco optional to generate documentation.

learn2learn/data/transforms.pyx
`filtre` -> `filter` in `CythonFusedNWaysKShots` on line 374.
=> Fix typo in FusedNWaysKShots task transform.

examples/text/news_topic_classification.py
Fixes #145 
update the text example with the new api. since ``benchmarks`` for text is not available yet so this pr is a bit verbose.
~~~shell
[PASTE HERE]
~~~
=> adapt to new api

examples/rl/metasgd_a2c.py
Fixes #167 
\alpha is now learned in Meta-SGD
=> fix: \alpha is now learned in Meta-SGD

learn2learn/vision/models.py
Unifies vision models to mimic torchvision's .features and .classifier API.
=> Add .features and .classifier to vision models.

learn2learn/utils.py, tests/unit/utils_test.py
Equivalent of #176 but for `l2l.update_module()`.
=> Fix update_module for shared parameters across submodules.

CHANGELOG.md, docs/pydocmd.yml, docs/source/paper_list.md, learn2learn/vision/benchmarks/mini_imagenet_benchmark.py, learn2learn/vision/benchmarks/tiered_imagenet_benchmark.py, learn2learn/vision/models/__init__.py, learn2learn/vision/models/cnn4.py, learn2learn/vision/models/resnet12.py
Adds ResNet12 and data augmentation for vision benchmarks.
~~~shell
test_adaptation (unit.algorithms.gbml_test.TestGBMLgorithm) ... ok
test_allow_nograd (unit.algorithms.gbml_test.TestGBMLgorithm) ... Traceback (most recent call last):
File …
=> Add ResNet12 and data augmentation for vision benchmarks.

CHANGELOG.md, learn2learn/vision/models/__init__.py, learn2learn/vision/models/cnn4.py
Adds the alias and additional argument, for convenience.
=> Add CNN4 alias to MiniImageNetCNN.

CHANGELOG.md, docs/pydocmd.yml, learn2learn/data/__init__.py, learn2learn/data/meta_dataset.pyx, tests/unit/data/metadataset_test.py
Fixes #55 
Adds `UnionMetaDataset` to combine multiple MetaDatasets into one.
~~~shell
test_adaptation (unit.algorithms.gbml_test.TestGBMLgorithm) ... ok
test_allow_nograd (unit.algorithms.gbml_test.TestGBMLgorithm) ... Traceback (most recent call last):
File …
=> Add UnionMetaDataset.

README.md
Adds an Arxiv badge to the README.
=> Add ArXiv badge.

examples/maml_sine.py
Created a ".py" file containing an example implementation of learn2learn's maml module on sine wave regression data.
The dataloader for the sine wave is imported from the torchmeta package.
~~~shell
[PASTE HERE]
~~~
=> add maml sine wave regression example

learn2learn/vision/models/cnn4.py
Small tweak to add channels argument to CNN4.
=> Add channels argument to CNN4.

.github/pull_request_template.md, .github/workflows/python_unittest.yaml, CHANGELOG.md, learn2learn/text/datasets/news_classification.py, setup.py
* Install some learn2learn dependencies before hand with pip in CI.
* Since pandas is only required for the news dataset, we make it optional.
* Update the contribution checklist in PR template.
=> Fix GitHub Workflow CI.

tests/unit/algorithms/maml_test.py
Adds a test for the fo-MAML implementation.
=> Tests for MAML first-order adaptation.

examples/vision/reptile_miniimagenet.py
Fixes #132 
Updates the reference implementation for Reptile. Hyper-parameters might need tuning for specific datasets.
=> Fix Reptile example.

CHANGELOG.md, learn2learn/vision/datasets/cu_birds200.py, learn2learn/vision/datasets/fgvc_aircraft.py
Add optional bounding box cropping for CUB, Aircraft.
=> Add optional bounding box cropping for CUB, Aircraft.

learn2learn/vision/datasets/cu_birds200.py, learn2learn/vision/datasets/fgvc_aircraft.py
=> Fix RGB colors for CUB200.

CHANGELOG.md, learn2learn/utils/__init__.py, tests/unit/utils_test.py
Discussed in slack.
Replace this line by a one sentence summary of your PR.
If necessary, use the following space to provide context or more details.
There seem to be some import errors, but I also get those errors on upstream master. So I suspect I might be able to ignore those. Let's see if the github CI tests pass.
=> Add keep_requires_grad flag to detach_module

examples/vision/supervised_pretraining.py
Quick fix to the supervised pretraining example, removes extra argument `ways`
=> Fix partion_task arguments in supervised pretraining example.

learn2learn/utils/__init__.py
Fixes #329
Fix minor issue in clone_module function.
=> Fix minor issue in clone_module function

learn2learn/vision/benchmarks/mini_imagenet_benchmark.py, learn2learn/vision/benchmarks/tiered_imagenet_benchmark.py
A couple of issues are being blocked by lint errors. This PR fixes them.
=> Fix lint errors.

CHANGELOG.md, learn2learn/vision/datasets/cifarfs.py, learn2learn/vision/datasets/fc100.py, learn2learn/vision/datasets/mini_imagenet.py, learn2learn/vision/datasets/tiered_imagenet.py
Fixes #260.
Changes mini-ImageNet targets to ints.
=> Fix mi targets

.github/workflows/python_unittest.yaml, learn2learn/vision/datasets/fgvc_aircraft.py
The `--install-option` is now deprecated in pip, so this attempts to circumvent it.
=> Fix Cython install in GitHub Actions
